import type { OrbitTherapist } from "@/lib/orbit-types";

const portrait = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=800&h=1000&q=85`;

export function defaultTherapists(): OrbitTherapist[] {
  return [
    {
      slug: "anita-shrestha",
      name: "Anita Shrestha",
      title: "Senior massage therapist",
      description: "Specialises in deep tissue and post-travel recovery with a calm, measured pace.",
      experience: "12 years experience",
      priceFromNpr: 4200,
      photo: portrait("photo-1559837294-2b711db19563"),
      photoAlt: "Anita Shrestha, massage therapist at Kaya Healing Spa",
    },
    {
      slug: "priya-gurung",
      name: "Priya Gurung",
      title: "Ayurvedic therapist",
      description: "Warm oil rituals, shirodhara, and traditional Ayurvedic body work.",
      experience: "10 years experience",
      priceFromNpr: 4800,
      photo: portrait("photo-1573496359142-b8d87734a5a2"),
      photoAlt: "Priya Gurung, Ayurvedic therapist",
    },
    {
      slug: "sunita-rai",
      name: "Sunita Rai",
      title: "Swedish & relaxation specialist",
      description: "Gentle full-body massage for guests who want quiet, steady pressure.",
      experience: "9 years experience",
      priceFromNpr: 4000,
      photo: portrait("photo-1580489944761-15a19d654956"),
      photoAlt: "Sunita Rai, relaxation massage therapist",
    },
    {
      slug: "maya-tamang",
      name: "Maya Tamang",
      title: "Hot stone & body care",
      description: "Hot stone placement, body scrubs, and circulation-focused sessions.",
      experience: "8 years experience",
      priceFromNpr: 4500,
      photo: portrait("photo-1594744803329-e58b31de8bf5"),
      photoAlt: "Maya Tamang, hot stone therapist",
    },
    {
      slug: "rebecca-limbu",
      name: "Rebecca Limbu",
      title: "Facial & skin therapist",
      description: "Natural facials, gentle extractions, and restorative skin rituals.",
      experience: "7 years experience",
      priceFromNpr: 3800,
      photo: portrait("photo-1438761681033-6461ffad8d80"),
      photoAlt: "Rebecca Limbu, facial therapist",
    },
    {
      slug: "karuna-bhandari",
      name: "Karuna Bhandari",
      title: "Thai & stretching therapist",
      description: "Thai-inspired stretching, joint mobilisation, and floor mat work.",
      experience: "11 years experience",
      priceFromNpr: 4400,
      photo: portrait("photo-1544005313-94ddf0286df2"),
      photoAlt: "Karuna Bhandari, Thai therapy specialist",
    },
    {
      slug: "elina-magar",
      name: "Elina Magar",
      title: "Couples & wellness rituals",
      description: "Coordinates couple rooms, synchronized massage, and unhurried packages.",
      experience: "6 years experience",
      priceFromNpr: 5200,
      photo: portrait("photo-1534528741775-53994a69daeb"),
      photoAlt: "Elina Magar, couples wellness therapist",
    },
    {
      slug: "sangita-kc",
      name: "Sangita KC",
      title: "Prenatal & gentle care",
      description: "Side-lying massage and lighter pressure for guests who need extra care.",
      experience: "8 years experience",
      priceFromNpr: 4100,
      photo: portrait("photo-1489424731084-a5d8b219a5bb"),
      photoAlt: "Sangita KC, prenatal massage therapist",
    },
    {
      slug: "nisha-pradhan",
      name: "Nisha Pradhan",
      title: "Aromatherapy specialist",
      description: "Custom blends, inhalation, and slow Swedish work with essential oils.",
      experience: "9 years experience",
      priceFromNpr: 4300,
      photo: portrait("photo-1508214751193-bcfd4ca60f91"),
      photoAlt: "Nisha Pradhan, aromatherapy therapist",
    },
    {
      slug: "devika-thapa",
      name: "Devika Thapa",
      title: "Head, neck & desk recovery",
      description: "Focused work for shoulders, neck, scalp, and tension from long travel or desk days.",
      experience: "10 years experience",
      priceFromNpr: 3900,
      photo: portrait("photo-1494790108377-be9c29b29330"),
      photoAlt: "Devika Thapa, neck and shoulder specialist",
    },
  ];
}
