import type { Service, ServiceCategory } from "./types";
import { serviceImagePath } from "./catalog-images";

function menuService(
  slug: string,
  name: string,
  category: ServiceCategory,
  tagline: string,
  overview: string,
  durationOptions: string[],
  priceFromNpr: number,
  image = serviceImagePath(slug),
  imageAlt?: string,
): Service {
  const match = durationOptions[0]?.match(/(\d+)\s*min/i);
  return {
    slug,
    name,
    category,
    summary: tagline.replace(/^\(|\)$/g, "").trim(),
    overview,
    durationMinutes: match ? Number(match[1]) : 60,
    durationOptions,
    priceFromNpr,
    priceIsPlaceholder: true,
    benefits: [],
    expect: [],
    recommendedFor: [],
    preparation: ["Arrive a little early", "Mention allergies, injuries, or areas to avoid"],
    image,
    imageAlt: imageAlt || `${name} at Kaya Healing Spa, Kathmandu`,
  };
}

/** Live spa menu — synced to Orbit when servicesMenuVersion bumps. */
export const defaultServices: Service[] = [
  // —— Massage ——
  menuService(
    "jet-lag-relief-massage",
    "Jet Lag Relief Massage",
    "massage",
    "(stress & headache relief)",
    "A 30-minute de-stressing back and shoulder massage precedes a 10-minute detox foot soak followed by 30 minutes of relaxing foot massage. Scents of essential oils and exotic Himalayan salt come together to fill your senses and leave you with a feeling of renewal.",
    ["60 min — NPR 4,500", "90 min — NPR 5,500"],
    4500,
  ),
  menuService(
    "lymphatic-drainage-massage",
    "Lymphatic Drainage Massage",
    "massage",
    "(therapeutic relaxation)",
    "Boost your immune system. Let us drain lactic acid, fatty acid and excess toxins. See and feel the result right after your session. This therapy begins with full body dry brush followed by soft rhythmic massage techniques to eliminate body and facial toxins.",
    ["60 min — NPR 4,500", "90 min — NPR 6,000"],
    4500,
  ),
  menuService(
    "four-hand-synchronize-massage",
    "Four Hand Synchronize Massage",
    "massage",
    "(double relaxation)",
    "Two therapists perform a synchronized full body massage bringing you to a deeper state of relaxation. An Ayurvedic tradition, this treatment is highly effective in balancing energy levels throughout the body.",
    ["60 min — NPR 6,000", "90 min — NPR 8,000"],
    6000,
  ),
  menuService(
    "back-neck-head-massage",
    "Back, Neck & Head Massage",
    "massage",
    "(back pain and headache relief)",
    "Tight muscles reduce circulation, letting waste products accumulate, which can leave you feeling fatigued and sore. This massage can release contracted muscles, increase circulation and relax the nervous system, flushing waste away and replacing it with oxygen and nutrients.",
    ["30 min — NPR 2,500", "60 min — NPR 4,000"],
    2500,
  ),
  menuService(
    "foot-massage",
    "Foot Massage",
    "massage",
    "(stimulates the nervous system)",
    "Sometimes tight muscles press on nerves, causing tingling, numbness, or more pain. Medium pressure on specific points on the feet stimulates the nervous system, relaxes muscle tension and supports the immune system.",
    ["30 min — NPR 2,500", "60 min — NPR 4,000"],
    2500,
  ),
  menuService(
    "himalayan-trekkers-massage",
    "Himalayan Trekker's Massage",
    "massage",
    "(deep relaxation)",
    "Relax and unwind with this therapeutic massage for the whole body. Our expert therapists use a combination of deep pressure massage and stretching that alleviates stiff muscles and joint pains while boosting blood circulation. Extremely beneficial after a trek or tiring physical exertion.",
    ["90 min — NPR 6,000", "120 min — NPR 7,500"],
    6000,
  ),
  menuService(
    "kaya-healing-therapy",
    "Kaya Healing Therapy",
    "massage",
    "(deep relaxation)",
    "Discover tranquility, healing and harmony with our specially designed Himalayan bowl therapy followed by full-body aromatherapy massage to release everyday stress and tension as well as enhance circulation and well-being. Feel a total sense of peaceful relaxation.",
    ["60 min — NPR 4,000", "90 min — NPR 5,500"],
    4000,
  ),
  menuService(
    "hot-stone-massage",
    "Hot Stone Massage",
    "massage",
    "(healing & relaxation)",
    "This holistic ritual uses warm stones to encourage balance, comfort and well-being. The heat penetrates deep into the body for a calming and relaxing experience.",
    ["60 min — NPR 4,000", "90 min — NPR 5,500"],
    4000,
  ),
  menuService(
    "thai-stretch-massage",
    "Thai Stretch Massage",
    "massage",
    "(deep relaxation)",
    "This non-oil massage focuses on muscle stretching and pressing to stimulate the natural flow of energy lines throughout the body. This treatment releases blocked energy and helps restore your natural balance, health and harmony.",
    ["60 min — NPR 4,000", "90 min — NPR 5,500"],
    4000,
  ),
  // —— Holistic ——
  menuService(
    "ayurvedic-massage",
    "Ayurvedic Massage",
    "holistic",
    "(muscle relaxation)",
    "Uses world-renowned classic massage techniques which release physical stress and fatigue. It combines vigorous and soothing massage movements adapted to your individual areas of tension. This massage is highly effective for muscle relaxation.",
    ["60 min — NPR 3,500", "90 min — NPR 5,000"],
    3500,
  ),
  menuService(
    "deep-tissue-massage",
    "Deep Tissue Massage",
    "holistic",
    "(muscle tension ease)",
    "This powerful massage penetrates the muscles to alleviate deep-seated tension and muscular stress. It re-aligns the deeper layers of muscle and connective tissue to release chronic tension.",
    ["60 min — NPR 4,000", "90 min — NPR 5,500"],
    4000,
  ),
  menuService(
    "nepali-aromatic-massage",
    "Nepali Aromatic Massage",
    "holistic",
    "(aches and tension relief)",
    "Combining vigorous and soothing massage movements with medium to firm pressure using warm aromatic oil, this massage melts away muscular aches and tension as well as relaxes the whole body and mind.",
    ["60 min — NPR 4,000", "90 min — NPR 5,500"],
    4000,
  ),
  menuService(
    "shirodhara-massage",
    "Shirodhara Massage",
    "holistic",
    "(deep relaxation)",
    "Calm the mind and spirit with this gentle Ayurvedic treatment. Warm oils are poured over the forehead, opening the third eye in a soothing flow. This treatment improves memory, reduces stress and anxiety, relieves insomnia and nourishes the hair and scalp.",
    ["90 min — NPR 6,500", "120 min — NPR 8,000"],
    6500,
  ),
  // —— Facial ——
  menuService(
    "hydra-facial",
    "Hydra Facial",
    "facial",
    "(skin moisturizing)",
    "Facial cleansing, tone, scrub, massage and mask. A facial treatment that encourages the skin to reveal its luminosity by reducing fatigue signs. Active ingredients smooth and moisturize the skin, leaving it looking and feeling younger.",
    ["60 min — NPR 5,000"],
    5000,
  ),
  menuService(
    "collagen-facial",
    "Collagen Facial",
    "facial",
    "(skin smoothing)",
    "Facial cleansing, tone, scrub, massage and mask. Works on the lymphatic system to relieve congestion within the tissues, increase muscle tone, tighten pores and brighten the eyes.",
    ["60 min — NPR 5,500"],
    5500,
  ),
  menuService(
    "mens-facial",
    "Men's Facial",
    "facial",
    "(skin detoxifying)",
    "Regenerate and strengthen the skin with this revitalizing, moisturizing and anti-aging treatment tailored for men's skin care goals. For optimal results, shave two hours prior to treatment.",
    ["60 min — NPR 5,000"],
    5000,
  ),
  menuService(
    "mini-facial",
    "Mini Facial",
    "facial",
    "(skin cleansing)",
    "Boost your skin cells' renewing power with collagen therapy that instantly sculpts facial contours and provides an infusion of hydration for an overall glow.",
    ["30 min — NPR 2,500"],
    2500,
  ),
  // —— Body care ——
  menuService(
    "himalayan-salt-glow",
    "Himalayan Salt Glow",
    "body-care",
    "(skin exfoliation)",
    "This stimulating scrub combines nutrient-rich salts from the shores of the Himalayas with essential oils. Together they eliminate dead surface cells and impurities. This full body exfoliation seals in natural oils, keeping your skin hydrated, supple and tingling with a healthy glow.",
    ["45 min — NPR 4,000"],
    4000,
  ),
  menuService(
    "coffee-aroma-scrub",
    "Coffee Aroma",
    "body-care",
    "(skin smoothing)",
    "Coffee aids in cleansing and smoothening the skin, while its refreshing aroma rejuvenates and revitalizes your senses. This body scrub cleanses the skin's surface, allowing nourishment to penetrate, leaving skin refreshed and baby-soft.",
    ["45 min — NPR 4,000"],
    4000,
  ),
  menuService(
    "herbal-magic-scrub",
    "Herbal Magic",
    "body-care",
    "(skin healing)",
    "A herbal body scrub that cleanses and smoothens the skin while botanical aromas rejuvenate your senses. Nourishment penetrates the pores, leaving skin refreshed and soft.",
    ["45 min — NPR 4,000"],
    4000,
  ),
  menuService(
    "detox-mud-wrap",
    "Detox Mud Wrap",
    "body-care",
    "(body detoxifying)",
    "Mud is one of the earth's most potent natural healing substances, containing bio-minerals, amino acids and plant hormones easily absorbed by skin. This treatment nourishes and rejuvenates, detoxifies and reduces skin inflammation.",
    ["60 min — NPR 5,000"],
    5000,
  ),
  menuService(
    "himalayan-sense-wrap",
    "Himalayan Sense",
    "body-care",
    "(skin firming)",
    "Himalayan cliff honey contains amino acids, antioxidants, vitamins and minerals that help fight free radicals. This rich combination of Himalayan minerals and vitamins helps eliminate water retention whilst improving circulation.",
    ["60 min — NPR 5,500"],
    5500,
  ),
  menuService(
    "manicure",
    "Manicure",
    "body-care",
    "Complete hand pampering",
    "Complete pampering for your hands, including massage and exfoliation, nail cleansing and care, a hot bath, and nail polish to complete your new look.",
    ["NPR 2,000"],
    2000,
  ),
  menuService(
    "pedicure",
    "Pedicure",
    "body-care",
    "Complete foot pampering",
    "Complete pampering for your feet, including massage and exfoliation, nail cleansing and care, a hot bath, and nail polish to complete your new look.",
    ["NPR 2,500"],
    2500,
  ),
  menuService(
    "mani-pedi-combo",
    "Mani Pedi Combo",
    "body-care",
    "Hands and feet together",
    "Complete pampering for hands and feet — massage, exfoliation, nail care, hot bath and polish.",
    ["NPR 4,000"],
    4000,
  ),
  menuService(
    "waxing-legs",
    "Waxing — Legs",
    "body-care",
    "(half or full leg)",
    "Enjoy the comfort of a private room and peace of mind. Our standards for hygiene and discretion are uncompromising and your health is our top priority.",
    ["Half leg — NPR 1,500", "Full leg — NPR 2,000"],
    1500,
  ),
  menuService(
    "waxing-arms",
    "Waxing — Arms",
    "body-care",
    "(half or full arm)",
    "Professional waxing in a clean, discreet treatment room with strict hygiene standards.",
    ["Half arm — NPR 1,500", "Full arm — NPR 2,000"],
    1500,
  ),
  menuService(
    "waxing-chest",
    "Waxing — Chest",
    "body-care",
    "Chest waxing",
    "Professional chest waxing with uncompromising hygiene and discretion.",
    ["NPR 2,000"],
    2000,
  ),
  menuService(
    "waxing-underarm",
    "Waxing — Underarm",
    "body-care",
    "Underarm waxing",
    "Quick, hygienic underarm waxing in a private room.",
    ["NPR 500"],
    500,
  ),
  menuService(
    "eyebrow-threading",
    "Eyebrow Threading",
    "body-care",
    "Eyebrow shaping",
    "Precise eyebrow threading with careful hygiene standards.",
    ["NPR 500"],
    500,
  ),
  // —— Wellness ——
  menuService(
    "sauna-steam-bath",
    "Sauna & Steam Bath",
    "wellness",
    "(heat therapy)",
    "Our sauna and steam rooms are available daily from 9am–10pm. Please advise our spa receptionist 20 minutes prior to arriving. For health and safety, drink plenty of water and do not consume alcohol before using the sauna or steam rooms.",
    ["30 min — NPR 1,500"],
    1500,
  ),
];

export const defaultServiceCategories: ServiceCategory[] = ["massage", "holistic", "facial", "body-care", "wellness"];
